edition: 1.0.0
name: container-puppeteer
access: "{{ access }}"
vars:
  region: cn-shenzhen
services:
  fc-puppeteer-customContainer-html2png:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: puppeteer-customContainer
        role:
          name: puppeteer-customContainerDefaultRole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
        internetAccess: true
      function:
        name: html2png-customContainer
        description: HTTP function powered by nodejs express
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/${your_namespace}/${your_repo}:${version}
        cAPort: 8080
        codeUri: ./src/
      triggers:
        - name: http-trigger-test
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
