# ------------------------------------
#   欢迎您使用阿里云函数计算 FC 组件进行项目开发
#   组件仓库地址/帮助文档：https://github.com/devsapp/fc
#   Yaml参考文档：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/yaml.md
#   关于：
#      - Serverless Devs和FC组件的关系、如何声明/部署多个函数、超过50M的代码包如何部署
#      - 关于.fcignore使用方法、工具中.s目录是做什么、函数进行build操作之后如何处理build的产物
#   等问题，可以参考文档：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/tips.md
#   关于如何做CICD等问题，可以参考：https://github.com/Serverless-Devs/Serverless-Devs/blob/master/docs/zh/cicd.md
#   有问题快来钉钉群问一下吧：33947367
# ------------------------------------
edition: 1.0.0
name: container-puppeteer
access: "{{ access }}"
vars:
  region: cn-hangzhou
services:
  fc-puppeteer:
    component: fc
    actions:
      pre-deploy:
        - component: fc build --use-docker --dockerfile ./code/Dockerfile
    props:
      region: ${vars.region}
      service:
        name: puppeteer
        internetAccess: true
      function:
        name: html2png
        description: HTTP function powered by nodejs express
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: "{{ acrRegistry }}"
        codeUri: ./code
      triggers:
        - name: http-t
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*