# ------------------------------------
#   欢迎您使用阿里云函数计算 FC 组件进行项目开发
#   组件仓库地址/帮助文档：https://github.com/devsapp/fc
#   Yaml参考文档：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/yaml.md
#   快速入门：
#      快速创建应用：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/quick_start_application.md
#      快速使用命令：https://github.com/devsapp/fc/blob/jiangyu-docs/docs/zh/quick_start_function.md
# ------------------------------------

edition: 1.0.0
name: container-puppeteer
access: "{{ access }}"
vars:
  region: cn-hangzhou
services:
  fc-puppeteer-customContainer-html2png:
    component: fc
    actions:
      pre-deploy:
        - run: s build --use-docker --dockerfile ./src/Dockerfile
          path: ./
    props:
      region: ${vars.region}
      service:
        name: puppeteer-customContainer
        internetAccess: true
      function:
        name: html2png-customContainer
        description: HTTP function powered by nodejs express
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/${your_namespace}/${your_repo}:${version}
        codeUri: ./src/
      triggers:
        - name: http-trigger-test
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
